name: 'tsoa-template'
services:
  postgres-dev:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=dev-password
      - POSTGRES_USER=dev-user
      - POSTGRES_DB=dev
    ports:
      - 54323:5432
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data

volumes:
  pgdata:
